### ISSUE TITLE
Update to python 3, django 3, and add recaptcha v3

### ISSUE THREAD

**Issue by 9mido** [a-roomana/django-multi-captcha-admin#3]
This package has not been updated for a while. Please update it.

Also add recaptcha v3

**Comment by Star-fly-Cheng** [comment]
> This package has not been updated for a while. Please update it.
> 
> Also add recaptcha v3

You can look at Pull requests. Just need to add some codes.

**Comment by a-roomana** [comment]
thank you so much.

the new version is uploaded
